# =========================================================
# Logging Konfiguration allgemein
# =========================================================

# OTel
quarkus.otel.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true

# Prometheus
quarkus.micrometer.export.prometheus.enabled=true

# =========================================================
# Logging Konfiguration DEV
# =========================================================
%dev.quarkus.log.console.level=DEBUG
%dev.quarkus.log.console.json=false
%dev.quarkus.log.console.json.enabled=false
%dev.quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p message=%m service=%X{service.name} env=%X{environment} host=%h traceId=%X{traceId} spanId=%X{spanId} corrId=%X{correlationId} http.method=%X{http.method} http.path=%X{http.path}%n

# =========================================================
# Logging Konfiguration PROD (und andere Umgebungen != DEV)
# =========================================================
%prod.quarkus.log.console.level=INFO
%prod.quarkus.log.console.json=true
%prod.quarkus.log.console.json.enabled=true
%prod.quarkus.log.console.json.pretty-print=true
