quarkus.http.port=0
quarkus.log.level=INFO

quarkus.application.name=loglib-it-service
quarkus.profile=test

quarkus.rest-client.downstream.url=http://localhost:${quarkus.http.test-port}

quarkus.otel.traces.exporter=none
quarkus.otel.metrics.exporter=none
